declare module 'styled-dropdown-component';
declare module 'styled-react-modal';
declare module 'react-datepicker';
declare module '*.svg'
declare module '*.png'
declare module '*.jpg'
declare module '*.jpeg'
declare module '*.gif'
declare module '*.bmp'
declare module '*.tiff'